# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.version.version)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr = np.zeros((10,10))
print('%d bytes' % (arr.size * arr.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
arr = np.arange(11)
arr = arr[::-1]
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
arr = np.nonzero([1, 2, 0, 0, 4, 0])
arr

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
arr = np.random.random((3, 3, 3))
arr

array([[[0.34056332, 0.50232402, 0.66684075],
        [0.45450816, 0.79388235, 0.91173744],
        [0.29588373, 0.29617953, 0.65926217]],

       [[0.85107078, 0.49683745, 0.99336962],
        [0.51697744, 0.86794583, 0.3342769 ],
        [0.02436691, 0.94430658, 0.78446445]],

       [[0.36431549, 0.2005618 , 0.92547015],
        [0.90397948, 0.74224002, 0.44129326],
        [0.27854315, 0.06051856, 0.3866802 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
arr = np.random.random((10, 10))
#print(arr)
arr.min(), arr.max()

(0.003528062365933282, 0.9813212720737716)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
arr = np.random.random(30)
arr.mean()

0.5052431179459057

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
arr = np.ones((6, 6))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
arr = np.ones((6, 6))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
arr = np.diag(1+np.arange(4), k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
arr = np.zeros((8,8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
arr = np.random.random((5,5))
arr = (arr - np.mean(arr))/(np.std(arr))
arr

array([[-0.14023605,  0.30413536,  0.0615429 , -0.81370903,  0.38883845],
       [-0.54194447,  0.40253295,  0.57749345,  0.5743819 , -0.17802044],
       [-1.05662625, -1.70712943,  1.71142435,  1.97540047, -1.16946426],
       [ 0.19248971, -1.35281154,  1.03860481, -0.67105521,  0.83520794],
       [ 1.60845877, -0.35606054, -1.80399308,  0.61749442, -0.4969552 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([('r', np.ubyte), ('g', np.ubyte), ('b', np.ubyte), ('a', np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
arr = np.dot(np.ones((5,3)), np.ones((3,2)))
arr

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
arr = np.arange(11)
arr[(3 < arr) & (arr < 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/tmp/ipykernel_37560/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/tmp/ipykernel_37560/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:
arr = np.random.uniform(-6,+6,6)
print(np.copysign(np.ceil(np.abs(arr)), arr))

[2. 6. 2. 6. 1. 1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [29]:
arr1 = np.random.randint(0,6,6)
arr2 = np.random.randint(0,6,6)
print(np.intersect1d(arr1,arr2))

[1 2]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [30]:
defaults = np.seterr(all="ignore")
arr = np.ones(1) / 0
arr

array([inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [33]:
yesterday, today, tomorrow

(numpy.datetime64('2022-10-01'),
 numpy.datetime64('2022-10-02'),
 numpy.datetime64('2022-10-03'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
arr = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(arr)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.ones(6)*1
B = np.ones(6)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5, -1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [36]:
arr = np.random.uniform(0,6,6)

print(arr - arr%1)
print(arr // 1)
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))

[1. 3. 4. 4. 5. 0.]
[1. 3. 4. 4. 5. 0.]
[1. 3. 4. 4. 5. 0.]
[1 3 4 4 5 0]
[1. 3. 4. 4. 5. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
arr = np.zeros((5,5))
arr += np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
def generate():
    for x in range(10):
        yield x
arr = np.fromiter(generate(), dtype=float, count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
arr = np.random.random(10)
arr.sort()
arr

array([0.00383981, 0.11566864, 0.19339106, 0.28916457, 0.32754233,
       0.49451986, 0.50828002, 0.57212075, 0.8042894 , 0.84356015])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
arr = np.arange(6)
np.add.reduce(arr)

15

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [42]:
A = np.random.randint(0,4,6)
B = np.random.randint(0,4,6)

equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [44]:
arr = np.ones(6)
arr.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
arr = np.random.random((10,2))
x,y = arr[:,0], arr[:,1]
R = np.sqrt(x**2 + y**2)
T = np.arctan2(y, x)
print(R)
print(T)

[0.82469633 0.47727245 0.8278946  1.03149004 0.81455928 0.9703163
 1.02331555 0.98455672 0.76049336 0.05691019]
[0.93918032 0.19819447 1.12363887 0.93694131 1.41573239 0.23051355
 0.41599023 0.26862343 1.50728088 0.19245477]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [46]:
arr = np.random.random(10)
arr[arr.argmax()] = 0
print(arr)

[0.48013136 0.85294899 0.6238397  0.27555537 0.42174072 0.27463451
 0.71036379 0.56603607 0.01550594 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [47]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [48]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [49]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [50]:
np.set_printoptions(threshold=float("inf"))
arr = np.zeros((4,6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [51]:
arr = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(arr-v)).argmin()
print(arr[index])

80


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [52]:
arr = np.zeros(6, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/tmp/ipykernel_37560/1828572333.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  arr = np.zeros(6, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [53]:
arr = np.random.random((10,2))
X,Y = np.atleast_2d(arr[:,0], arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.62603894 0.4112468  0.43953989 0.55640079 0.59979681
  0.56956763 0.90037953 0.22934464 0.92980397]
 [0.62603894 0.         0.21495177 0.47150221 0.15605371 0.61799223
  0.50428965 0.27458927 0.56616446 0.34361909]
 [0.4112468  0.21495177 0.         0.34581173 0.18893343 0.54131367
  0.44259638 0.48913295 0.3782422  0.53229351]
 [0.43953989 0.47150221 0.34581173 0.         0.52513934 0.85257647
  0.76846907 0.68766786 0.57021909 0.63415363]
 [0.55640079 0.15605371 0.18893343 0.52513934 0.         0.46195609
  0.34844309 0.38749544 0.44831529 0.4915124 ]
 [0.59979681 0.61799223 0.54131367 0.85257647 0.46195609 0.
  0.11491735 0.80828755 0.37131882 0.9436804 ]
 [0.56956763 0.50428965 0.44259638 0.76846907 0.34844309 0.11491735
  0.         0.69486588 0.35273479 0.82877281]
 [0.90037953 0.27458927 0.48913295 0.68766786 0.38749544 0.80828755
  0.69486588 0.         0.83113687 0.18087637]
 [0.22934464 0.56616446 0.3782422  0.57021909 0.44831529 0.37131882
  0.35273479 0.83113

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [54]:
arr = (np.random.rand(10)*100).astype(np.float32)
Y = arr.view(np.int32)
Y[:] = arr
print(Y)

[27 91 22 64 52 66 74 74 18 73]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [55]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
arr = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(arr)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [56]:
arr = np.arange(6).reshape(3,2)
for index, value in np.ndenumerate(arr):
    print(index, value)
for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [57]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [58]:
n = 6
p = 2
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace=False),1)
print(arr)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [59]:
arr = np.random.rand(5, 10)

# Recent versions of numpy
Y = arr - arr.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = arr - arr.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.41488917  0.00887938  0.13581686 -0.01470434  0.13284825 -0.19050765
   0.01055798 -0.2947298   0.03970316 -0.242753  ]
 [ 0.18979947 -0.18912357  0.18974827 -0.49727552 -0.32224915  0.36187291
  -0.32383868  0.36543034  0.39149956 -0.16586363]
 [ 0.09654395  0.27571355 -0.12041768  0.4896836  -0.084201   -0.36714334
  -0.03590356  0.0290037   0.11423441 -0.39751363]
 [-0.00266191  0.38216297  0.14067015 -0.39892013 -0.30833136 -0.2993581
   0.1982063  -0.31107348  0.42776022  0.17154535]
 [-0.00645917  0.11695689  0.01732586  0.00777731  0.53268768 -0.37295186
  -0.26760661 -0.23790388  0.5723062  -0.36213243]]


#### 59. How to sort an array by the nth column? (★★☆)

In [60]:
arr = np.random.randint(0,10,(3,3))
print(arr)
print(arr[arr[:,1].argsort()])

[[7 1 9]
 [6 9 8]
 [2 5 3]]
[[7 1 9]
 [2 5 3]
 [6 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [61]:
arr = np.random.randint(0,3,(3,10))
print((~arr.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [62]:
arr = np.random.uniform(0,1,10)
a = 0.5
m = arr.flat[np.abs(arr - a).argmin()]
print(m)

0.5522492929497488


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [63]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [64]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

arr = NamedArray(np.arange(6), "range_6")
print (arr.name)

range_6


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [65]:
arr = np.ones(10)
I = np.random.randint(0,len(arr),20)
arr += np.bincount(I, minlength=len(arr))
print(arr)

[3. 3. 7. 2. 2. 1. 3. 3. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [66]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [67]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [68]:
arr = np.random.randint(0,10,(3,4,3,4))
sum = arr.sum(axis=(-2,-1))
print(sum)

[[55 41 59 53]
 [50 70 43 38]
 [45 55 56 63]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [69]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.346035
1    0.372841
2    0.616701
3    0.445243
4    0.666440
5    0.497601
6    0.573541
7    0.460159
8    0.468287
9    0.501520
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [70]:
arr1 = np.random.uniform(0,1,(5,5))
arr2 = np.random.uniform(0,1,(5,5))

np.diag(np.dot(arr1, arr2))

array([1.47789354, 1.01934532, 1.21376327, 2.13793426, 0.93485577])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [71]:
arr = np.array([1,2,3,4,5])
nz = 3
arr0 = np.zeros(len(arr) + (len(arr)-1)*(nz))
arr0[::nz+1] = arr
print(arr0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [72]:
arr1 = np.ones((5,5,3))
arr2 = np.ones((5,5))
print(arr1 * arr2[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 72. How to swap two rows of an array? (★★★)

In [73]:
arr = np.arange(36).reshape(6,6)
arr[[0,1]] = arr[[1,0]]
print(arr)

[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [74]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 48) ( 2, 62) ( 9, 75) (15, 28) (15, 48) (18, 29) (18, 79) (27, 39)
 (27, 54) (28, 48) (29, 79) (31, 34) (31, 41) (34, 41) (38, 40) (38, 45)
 (39, 54) (39, 55) (39, 65) (40, 45) (48, 62) (48, 74) (48, 79) (55, 65)
 (63, 80) (63, 98) (74, 79) (75, 75) (80, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [75]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [76]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
arr = np.arange(20)
print(moving_average(arr, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [77]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
arr = rolling(np.arange(10), 3)
print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [78]:
arr = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)

arr = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)

array([ 0.78353551, -0.15649978,  0.35625525, -0.76556712,  0.30660912,
        0.60873954, -0.65312179, -0.14300961, -0.09818765,  0.5235344 ,
        0.29931437, -0.71536365,  0.4003755 ,  0.18978764, -0.28316322,
       -0.39043878,  0.28312496, -0.62483779,  0.95538311, -0.89188923,
        0.86690215,  0.72357652,  0.66419996, -0.73824789, -0.42804605,
       -0.667655  ,  0.14611554, -0.02068066,  0.69982656,  0.43553846,
        0.43998859, -0.0753937 ,  0.58856687,  0.30486319, -0.55190939,
        0.86402589,  0.93922071,  0.25385918,  0.29586975,  0.03430173,
       -0.49992835,  0.78410208,  0.26135756,  0.16523972, -0.3381223 ,
       -0.31798265,  0.18784046, -0.87120684,  0.74206809, -0.26511323,
       -0.77550802,  0.49301828, -0.26440741, -0.57527208,  0.67459263,
        0.66923738, -0.71605514, -0.88909208,  0.27178681,  0.12683361,
        0.14632895, -0.29829286, -0.78518898, -0.6957727 ,  0.60994372,
        0.5460249 ,  0.26543165, -0.53878522, -0.26227165, -0.26

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [79]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[13.86474294  3.05889562  3.87108253  3.72002888  2.33727123  8.31708498
 14.16700371  3.57511633  1.06529672  4.55289007]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [80]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[18.04469219 14.15120408 10.25676497  4.6232534  15.75975598  8.75282361
   2.99536645  1.37588897 10.4424406   3.49702241]
 [ 0.36686231  0.34445924  6.24883063  7.34927721  1.77120067  9.15980296
  14.8205326   2.24826852  7.19050276  5.27996585]
 [10.56952636 11.68742686  2.12910832  3.87576192  8.13507666  1.71738337
   4.27870709  3.28613541  4.80416486  4.13563625]
 [ 7.22990272  1.99420169  1.1892657   6.57278338  5.22468576  2.68921136
   8.13669285  6.42335317  1.97592814  1.64569262]
 [ 5.87445513  2.56506193  0.60322502  5.51045341  3.78338263  3.81529779
   9.38364766  4.18144199  2.49365412  0.82683891]
 [ 4.71880674  2.03171878  1.81199887  5.80546639  2.6134202   4.92538086
  10.51899819  3.66991846  3.4409227   1.84376414]
 [ 5.53869353  8.90035132  2.98725594  2.04377502  3.06879191  3.18350821
   9.25411315  4.87435754  0.44971665  8.06484868]
 [ 8.27840782 16.54147871  2.11887312 10.24947398  5.47432395  0.38580387
   6.11115617 12.41306168  5.85771319 12.4751243 ]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [81]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 1 7 5 1 2 0 2 4 5]
 [7 4 6 1 8 5 2 5 6 7]
 [0 3 1 6 8 6 3 4 8 9]
 [8 2 7 8 4 9 2 4 9 6]
 [7 1 1 9 1 5 2 5 6 9]
 [8 7 8 6 2 2 5 6 9 4]
 [8 9 9 2 1 4 2 3 2 5]
 [5 8 2 0 9 4 5 3 0 7]
 [1 2 0 7 8 3 2 3 2 9]
 [2 3 8 9 9 5 4 2 0 1]]
[[0 0 0 0 0]
 [0 7 1 7 5]
 [0 7 4 6 1]
 [0 0 3 1 6]
 [0 8 2 7 8]]


/tmp/ipykernel_37560/1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [82]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [83]:
arr = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(arr) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [84]:
arr = np.random.randint(0,10,50)
print(np.bincount(arr).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [85]:
arr = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (arr.shape[0]-3)
j = 1 + (arr.shape[1]-3)
C = stride_tricks.as_strided(arr, shape=(i, j, n, n), strides=arr.strides + arr.strides)
print(C)

[[[[2 4 4]
   [4 4 4]
   [4 1 3]]

  [[4 4 2]
   [4 4 0]
   [1 3 3]]

  [[4 2 3]
   [4 0 0]
   [3 3 0]]

  [[2 3 2]
   [0 0 2]
   [3 0 1]]

  [[3 2 4]
   [0 2 1]
   [0 1 3]]

  [[2 4 2]
   [2 1 2]
   [1 3 0]]

  [[4 2 1]
   [1 2 3]
   [3 0 3]]

  [[2 1 3]
   [2 3 2]
   [0 3 2]]]


 [[[4 4 4]
   [4 1 3]
   [0 4 0]]

  [[4 4 0]
   [1 3 3]
   [4 0 1]]

  [[4 0 0]
   [3 3 0]
   [0 1 3]]

  [[0 0 2]
   [3 0 1]
   [1 3 1]]

  [[0 2 1]
   [0 1 3]
   [3 1 3]]

  [[2 1 2]
   [1 3 0]
   [1 3 4]]

  [[1 2 3]
   [3 0 3]
   [3 4 0]]

  [[2 3 2]
   [0 3 2]
   [4 0 3]]]


 [[[4 1 3]
   [0 4 0]
   [1 2 0]]

  [[1 3 3]
   [4 0 1]
   [2 0 1]]

  [[3 3 0]
   [0 1 3]
   [0 1 3]]

  [[3 0 1]
   [1 3 1]
   [1 3 4]]

  [[0 1 3]
   [3 1 3]
   [3 4 3]]

  [[1 3 0]
   [1 3 4]
   [4 3 1]]

  [[3 0 3]
   [3 4 0]
   [3 1 1]]

  [[0 3 2]
   [4 0 3]
   [1 1 2]]]


 [[[0 4 0]
   [1 2 0]
   [4 2 2]]

  [[4 0 1]
   [2 0 1]
   [2 2 2]]

  [[0 1 3]
   [0 1 3]
   [2 2 3]]

  [[1 3 1]
   [1 3 4]
   [2 3 3]]

  [[3 1 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [86]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  3 15 16 18]
 [ 3  4  4  8  3]
 [15  4  4 42 12]
 [16  8 42  8 10]
 [18  3 12 10  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [87]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [88]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [89]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [90]:
arr = np.arange(10000)
np.random.shuffle(arr)
n = 5
print(arr[np.argsort(arr)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [91]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [92]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [93]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.22 s ± 242 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
554 ms ± 71.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
466 ms ± 55.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [94]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [95]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[0 4 0]
 [2 2 1]
 [1 0 3]
 [1 1 2]
 [1 4 1]
 [2 0 0]
 [1 2 3]
 [1 1 2]
 [2 0 2]
 [2 1 0]]
[[0 4 0]
 [2 2 1]
 [1 0 3]
 [1 1 2]
 [1 4 1]
 [2 0 0]
 [1 2 3]
 [1 1 2]
 [2 0 2]
 [2 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [96]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [97]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [98]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[3.43142992e-02, 1.50426588e-01, 2.19608548e-03, 3.61463391e-02,
        2.06085362e-01, 1.18306010e-01, 6.59920912e-02, 1.01649018e-01,
        7.84116699e-02, 7.70519542e-02],
       [1.51586212e-01, 6.64521708e-01, 9.70138653e-03, 1.59679397e-01,
        9.10398877e-01, 5.22626439e-01, 2.91525439e-01, 4.49042816e-01,
        3.46389939e-01, 3.40383285e-01],
       [1.49154331e-02, 6.53860860e-02, 9.54574826e-04, 1.57117678e-02,
        8.95793448e-02, 5.14242001e-02, 2.86848529e-02, 4.41838871e-02,
        3.40832844e-02, 3.34922553e-02],
       [1.30685693e-01, 5.72898278e-01, 8.36377137e-03, 1.37663000e-01,
        7.84874207e-01, 4.50567353e-01, 2.51330273e-01, 3.87129348e-01,
        2.98630123e-01, 2.93451659e-01],
       [8.21997890e-02, 3.60346389e-01, 5.26071543e-03, 8.65884343e-02,
        4.93676796e-01, 2.83401652e-01, 1.58083834e-01, 2.43499882e-01,
        1.87834893e-01, 1.84577699e-01],
       [9.63657912e-03, 4.22447129e-02, 6.16732732e-04, 1.01510759e-02,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [99]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [100]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [101]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[0.08361105 0.43097872]
